version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: demo-web
    ports:
      - "8001:80"
    depends_on:
      - app

  app:
    image: openjdk
    volumes:
      - demo-volume:/app
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: demo1234

volumes:
  demo-volume:
